
services:
  backend:
    build:
      context: ./backend/SecureService
      dockerfile: Dockerfile
    container_name: secure-service-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DB_CON=server=mysql;database=SecureService;user=root;password=rootpassword;
      - ConnectionStrings__IS_ENCRYPTED=0
      - GAME_SERVICE=http://game-service:8000/
      - Jwt__Key=zO53wibJ2ga4wu2zgOppgvBQS8WrAVdf76gsHUrwDoY=kNmITYFYcn4s/yIC4jtgUw==
      - Jwt__Issuer=SecureService
      - AES_ENCRYPTION_KEY=40YPHs5wzB/Q5Blg7EN5h75pHzut9TkvUYUOItfMdP4=+EQ/v7/URS2b8dgIpx6ekQ==
      - WEBSECRET_KEY=default-secret-key-12ou9023
    networks:
      - secure-network
    volumes:
      - ./backend/Error:/app/Error

  mysql:
    image: mysql:8.0
    container_name: secure-service-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SecureService
    ports:
      - "9090:3306"
    volumes:
      - ./Database/mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - secure-network
    command: --default-authentication-plugin=mysql_native_password

  game-service:
    build:
      context: ./backend/GameService
      dockerfile: Dockerfile
    container_name: game-service
    ports:
      - "8000:8000"
    networks:
      - secure-network
    environment:
      - WEBSECRET_KEY=default-secret-key-12ou9023

networks:
  secure-network:
    driver: bridge
    
volumes:
  mysql_data: